### ISSUE TITLE
preserve across sessions?

### ISSUE THREAD

**Issue by Dapuva76** [alphapapa/dogears.el#22] opened 2024-02-01 12:29 UTC
Is there a way to preserve the contents of dogears-list across sessions?

**Comment by alphapapa** [comment] 2024-02-01 22:36
It's not intended for that, but you could try using `savehist` to save its value.  Beyond that, if it's really a requested feature, we could use `persist` to do it.

**Comment by hab25** [comment] 2024-04-18 02:51
duplicate of https://github.com/alphapapa/dogears.el/issues/4

**Closed** 2024-04-18 05:28 UTC
