### ISSUE TITLE
dogears-index can become negative

### ISSUE THREAD

**Issue by akirak** [alphapapa/dogears.el#16] opened 2022-09-28 19:50 UTC
When you repeatedly run `dogears-forward`, the index can become negative:

> Dogears: Forward to -14/6

`(nth N LIST)` returns the first element of the list if N is less than zero.

**Comment by alphapapa** [comment] 2022-09-29 18:14
Thanks.  I think this is a duplicate of #15.

**Closed by alphapapa** 2022-09-29 18:14 UTC
